### PR TITLE
Update imap-proto and test that "IMAP4REV1" capability is accepted

### PR DESCRIPTION
**Pull request by link2xt**
See issue https://github.com/djc/tokio-imap/issues/54

### CODE REVIEW

**Comment by link2xt** [comment]
Waiting for https://github.com/djc/tokio-imap/issues/57 to update dependency

**Comment by jonhoo** [comment]
@link2xt great -- just ping me when it lands and I'll merge?

**Comment by link2xt** [comment]
@jonhoo Updated to release 0.9.0.

**Comment by jonhoo** [comment]
Thanks!

**Comment by jonhoo** [comment]
Published in `2.0.0` :tada:

**Pull request merged**
