### PR TITLE
Implement From<String> for QuotaResourceName

### PR DESCRIPTION
**Pull request by urkle**
In using the quota feature in my application (finally) I noticed that I was running into life-time specifier issues trying to convert my input String into a QuotaResourceLimit through the Into<QuotaResourceName> argument.

I had to resort to re-implementing my own match line to convert into an Owned QuotaResourceName.

This PR adds an implementation of From<String> for QuotaResourceName<'_> so strings can be utilized as well as &str.

- - -
This change is [Reviewable](https://reviewable.io/reviews/jonhoo/rust-imap/272)

### CODE REVIEW

**Comment by jonhoo** [comment]
Hmm, this doesn't seem quite right — it means there's no way to _avoid_ turning it into an owned string. Wouldn't it be better to `impl From<String> for QuotaResourceName<'static>` in addition instead?

**Comment by urkle** [comment]
> Hmm, this doesn't seem quite right — it means there's no way to _avoid_ turning it into an owned string. Wouldn't it be better to `impl From<String> for QuotaResourceName<'static>` in addition instead?

Yup.. that makes better sense.  I knew this was "fishy", just wasn't sure how to easily fix it.

**Comment by urkle** [comment]
@jonhoo updated

**Review by jonhoo — APPROVED** [review]
Perfect, thank you!

**Pull request merged**
