### PR TITLE
server greeting doc and timeout example

### LINKED ISSUE #167: imap::connect timeout
I have a specific server with a long connection time and would like to configure a timeout for that, specifically for the `imap::connect` function. 

From looking at the documentation and source code, my current understanding is that `imap::connect` uses [`TcpStream::connect`](https://doc.rust-lang.org/std/net/struct.TcpStream.html#method.connect). There is also an alternative [`TcpStream::connect_timeout`](https://doc.rust-lang.org/std/net/struct.TcpStream.html#method.connect_timeout). Would it be useful to either add a timeout function argument to `imap::connect` or to mimic `TcpStream` and an `imap::connect_timeout` alternative?

### PR DESCRIPTION
**Pull request by wookietreiber**
fixes #167

---
This change is [Reviewable](https://reviewable.io/reviews/jonhoo/rust-imap/168)

### CODE REVIEW

**Comment by jonhoo** [comment]
This is great, thank you! Although it looks like the tests are failing?

**Comment by wookietreiber** [comment]
The docs were all messed up because I forgot to include all the ceremony for the doc tests to compile.

**Comment by wookietreiber** [comment]
Now that those are gone, there seem to be some unrelated problems. Looks like something with macros. Don't know if I can do something about that, though, @jonhoo would you please take a look?

**Comment by jonhoo** [comment]
Ah, interesting... I'm working to fix those in https://github.com/jonhoo/rust-imap/pull/169

**Comment by jonhoo** [comment]
Could you try merging master now?

**Comment by wookietreiber** [comment]
Rebased. Now, one of the FreeBSD tests segfaulted. It doesn't seem to show which one, unfortunately. It says: to rerun, pass `--lib` and I only changed docs and examples, which were successful.

@jonhoo Did the FreeBSD segfault also occur with the commits I rebased onto?

**Comment by jonhoo** [comment]
The FreeBSD failure is, as far as I can tell, a separate issue. So I went ahead and merged, thanks!

**Pull request merged**
