### PR TITLE
fix(client): handle single "+" in auth server response 

### PR DESCRIPTION
**Pull request by dignifiedquire**
Some servers (yandex) will send a single `"+"` as response when using XOAUTH2. 

(the first commit is from #144, can be ignored here)

### CODE REVIEW

**Comment by jonhoo** [comment]
Huh, this seems pretty weird. If the server challenge is empty, how can a challenge-response handshake even take place? What does the client provide?

**Comment by dignifiedquire** [comment]
Nothing, xoauth2 doesn’t use the challenge for both google and yandex.

**Comment by hpk42** [comment]
anything blocking the merge of this branch?

**Comment by jonhoo** [comment]
It's blocking on #144 :)

**Comment by jonhoo** [comment]
If you can resolve the conflicts with master (as a result of #144 being merged), I'd be happy to merge this!

**Comment by dignifiedquire** [comment]
thanks, should be fixed now

**Comment by jonhoo** [comment]
Published in `2.0.0` :tada:

**Pull request merged**
